# .swiftlint.yml

disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement

opt_in_rules: # some rules are only opt-in
  - empty_count

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - vendor

analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

force_cast: warning
force_try:
  severity: warning
line_length: 110
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 4 # only warning
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode"
