# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'LearnCICDSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LearnCICDSwift
  pod 'Alamofire'
  pod 'RealmSwift'


  target 'LearnCICDSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LearnCICDSwiftUITests' do
    # Pods for testing
  end

end
